<!DOCTYPE html>
<html lang="en">
<head>
    <title>test-site.com.ua</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style>
        .ownCustomPost {
            text-align: justify !important;
            color: #00264d !important;
            text-decoration: none;

        }
        .ownCustomDate {
            font-style: italic !important;
        }

        .ownCustomTitle {
            color: #003459 !important;
        }

        .modal-header, h4, .close {
            background-color: #669988;
            color:white !important;
            text-align: center;
            font-size: 30px;
        }
        .modal-footer {
            background-color: #AABBAA;
        }

        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        footer {
            background-color: #AABBAA;
            padding: 25px;
        }

        .carousel-inner img {
            width: 100%;
            margin: auto;
            min-height:200px;
        }

        @media (max-width: 600px) {
            .carousel-caption {
                display: none;
            }
        }
    </style>
</head>
<body>
<!--start NAVBAR-->
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">FRESH NEWS</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">IT news<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Programming news</a></li>
                        <li><a href="#">System administration news</a></li>
                        <li><a href="#">Robotics news</a></li>
                    </ul>
                </li>
                <li><a href="#">Fashion news</a></li>
                <li><a href="#">Politics news</a></li>
                <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Analitics<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">IT analitics<span class="caret"></span></a>
                            <!--перестало розкриватись!!!-->
                            <ul class="dropdown-menu ">
                                <li><a href="#">Programming analitics</a></li>
                                <li><a href="#">System administration analitics</a></li>
                                <li><a href="#">Robotics analitics</a></li>
                            </ul>
                        </li>
                        <li><a href="#">Fashion analitics</a></li>
                        <li><a href="#">Politics analitics</a></li>
                    </ul>
                </li>
            </ul>

            <form class="navbar-form navbar-right" action="/action_page.php">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </div>
                </div>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                <li><a href="#" id="startModalLogin"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            </ul>
        </div>
    </nav>
<!--end NAVBAR-->
<br>
<!-- start MODAL LOGIN -->
    <div class="container">
        <!-- Modal -->
        <div class="modal fade" id="modalLogin" role="dialog">
            <div class="modal-dialog">

                <!-- Modal login content-->
                <div class="modal-content">
                    <div class="modal-header" style="padding:35px 50px;">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4><span class="glyphicon glyphicon-lock"></span> Login</h4>
                    </div>
                    <div class="modal-body" style="padding:40px 50px;">
                        <form role="form" method="post">
                            <div class="form-group">
                                <label for="usrname"><span class="glyphicon glyphicon-user"></span> Username</label>
                                <input type="text" class="form-control" id="usrname" placeholder="Enter email">
                            </div>
                            <div class="form-group">
                                <label for="psw"><span class="glyphicon glyphicon-eye-open"></span> Password</label>
                                <input type="text" class="form-control" id="psw" placeholder="Enter password">
                            </div>
                            <div class="checkbox">
                                <label><input type="checkbox" value="" checked>Remember me</label>
                            </div>
                            <button type="submit" class="btn btn-success btn-block" style="background-color:#669988; border:none;"><span class="glyphicon glyphicon-off"></span> Login</button>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-danger btn-default pull-left" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
                        <p>Not a member? <a href="#">Sign Up</a></p>
                        <p>Forgot <a href="#">Password?</a></p>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <script>
        $(document).ready(function(){
            $("#startModalLogin").click(function(){
                $("#modalLogin").modal();
            });
        });
    </script>
<!-- end MODAL LOGIN-->

    <br>
<!-- start CONTENT-->
    <div class="container text-center">
        <h3>Last news</h3><br>
        <div class="row">
            <div class="col-sm-2">
                <div class="well">
                    <p>Left advertising</p>
                </div>
                <div class="well">
                    <p>Left advertising</p>
                </div>
                <div class="well">
                    <p>Left advertising</p>
                </div>
                <div class="well">
                    <p>Left advertising</p>
                </div>
            </div>
            <!--start CARUSEL-->
            <div class="container col-sm-8">
                <div id="myCarousel" class="carousel slide" data-ride="carousel" >
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                        <li data-target="#myCarousel" data-slide-to="1"></li>
                        <li data-target="#myCarousel" data-slide-to="2"></li>
                        <li data-target="#myCarousel" data-slide-to="3"></li>
                    </ol>

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner">

                        <div class="item active">
                            <img src="/views/image/winter.jpg" alt="Winter" style="width:100%;">
                            <div class="carousel-caption">
                                <h3>Winter</h3>
                                <p>Winter is always so much fun!</p>
                            </div>
                        </div>

                        <div class="item">
                            <img src="/views/image/summer_park.jpg" alt="Summer park" style="width:100%;">
                            <div class="carousel-caption">
                                <h3>Summer park</h3>
                                <p>Greate summer park</p>
                            </div>
                        </div>

                        <div class="item">
                            <img src="/views/image/waterfall.jpg" alt="Waterfall" style="width:100%;">
                            <div class="carousel-caption">
                                <h3>Waterfall</h3>
                                <p>Wonderful waterfall</p>
                            </div>
                        </div>

                        <div class="item">
                            <img src="/views/image/forest.jpg" alt="Waterfall" style="width:100%;">
                            <div class="carousel-caption">
                                <h3>Forest</h3>
                                <p>Beautiful forest</p>
                            </div>
                        </div>

                    </div>

                    <!-- Left and right controls -->
                    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#myCarousel" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <!--end CARUSEL-->
            </div>
            <div class="col-sm-2">
                <div class="well">
                    <p>Right advertising</p>
                </div>
                <div class="well">
                    <p>Right advertising</p>
                </div>
                <div class="well">
                    <p>Right advertising</p>
                </div>
                <div class="well">
                    <p>Right advertising</p>
                </div>
            </div>
        </div>
    </div>
<!--end CONTENT-->

<!-- start MODAL SUBSCRIPTION-->
<?php
    include(ROOT . DS . 'views' . DS . 'site' . DS . 'subscription.phtml');
?>
<!-- end MODAL SUBSCRIPTION-->


<!-- start MODAL EXIT-->
<p id="startModalExit"></p>
<div class="container">
    <!-- Modal -->
    <div class="modal fade" id="modalExit" role="dialog">
        <div class="modal-dialog">

            <!-- Modal exit content-->
            <div class="modal-content">
                <div class="modal-header" style="padding:35px 50px;">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4><span class="glyphicons glyphicons-exit"></span> Exit</h4>
                </div>
                <div class="modal-body" style="padding:40px 50px;">
                    <button type="submit" class="btn btn-danger btn-default pull-left " data-dismiss="modal" id="endModalSubscription"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
                    <button type="button" class="btn btn-primary pull-right" style="background-color:#669988; border:none;"> Exit</button>
                </div>
                <div class="modal-footer">

                </div>
            </div>

        </div>
    </div>
</div>
<script>

    // епізодично спрацьовує при спробі закрити вкладку браузера з сайтом

    function exitFunc1() {
        return confirm('Exit????????');
    }
    window.onbeforeunload = exitFunc1;


    function exitFunc2() {
        return confirm('Exit???');
    }
    window.unload = exitFunc2;


</script>
<!-- end MODAL EXIT -->

</body>
</html>