<head>
    <title>test-site.com.ua</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style>
        .modal-header, h4, .close {
            background-color: #669988;
            color:white !important;
            text-align: center;
            font-size: 30px;
        }
        .modal-footer {
            background-color: #AABBAA;
        }

        footer {
            background-color: #AABBAA;
            padding: 25px;
        }

        .carousel-inner img {
            width: 100%;
            margin: auto;
            min-height:200px;
        }

    </style>
</head>

<!-- start MODAL SUBSCRIPTION-->
<p id="startModalSubscription"></p>
<div class="container">
    <!-- Modal -->
    <div class="modal fade" id="modalSubscription" role="dialog">
        <div class="modal-dialog">

            <!-- Modal subscription content-->
            <div class="modal-content">
                <div class="modal-header" style="padding:35px 50px;">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4><span class="glyphicon glyphicon-envelope"></span> Subscription</h4>
                </div>
                <div class="modal-body" style="padding:40px 50px;">
                    <form role="form" action="#" method="post">
                        <div class="form-group">
                            <label for="email">Email:</label>
                            <input type="email" class="form-control" id="email" placeholder="Enter email" name="email" >
                        </div>
                        <div class="form-group">
                            <label for="usr">Name:</label>
                            <input type="text" class="form-control" id="usr" placeholder="Enter name" >
                        </div>
                        <div class="form-group">
                            <label for="usr">Surname:</label>
                            <input type="text" class="form-control" id="usr" placeholder="Enter surname" >
                        </div>
                        <button type="submit" class="btn btn-success btn-block" style="background-color:#669988; border:none;"><span class="glyphicon glyphicon-envelope"></span> Subscription</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger btn-default pull-left" data-dismiss="modal" id="endModalSubscription"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
                </div>
            </div>

        </div>
    </div>
</div>
<script>
    $(document).ready(function(){

        // показати модальне вікно через 15 секунд перебування на сайті
        window.setTimeout(function () {
            $("#modalSubscription").modal("show");
        }, 15000);

        // сховати модальне вікно
        $("#endMmodalSubscription").click(function(){
            $("#modalSubscription").modal("hide");
        });
    });
</script>
<!-- end MODAL SUBSCRIPTION -->
