<?php
    include(ROOT.DS.'views'.DS.'layouts'.DS.'default.phtml');
?>
    <section>
        <a name="lastnews"></a>
        <div>
            <?php foreach ($lastNews as $result) : ?>
                <div>
                    <a name="lastnewsList"></a>
                    <h2 class="ownCustomTitle"><a href="<?php echo $result['id'];?>"><?php echo $result['title'];?></a></h2>
                    <p class="ownCustomDate"><?php echo $result['date'];?></p>

                    <div class="ownCustomPost">
                        <p><?php echo $result['short_content'];?></p>
                    </div>

                    <div class="meta">
                        <p class="links"><a href="/lastnews/<?php echo $result['id']; ?>" class="comments">Read more...</a></p>
                    </div>

                </div>
            <?php endforeach; ?>
        </div>
    </section>